title: HCM Guru
description: Документация по инструментам для WebSoft HCM разработчиков.
theme: just-the-docs

url: https://just-the-docs.github.io

last_modified_date: true

ga_tracking: G-5MWDB6X775
ga_tracking_anonymize_ip: true

callouts:
  warning:
    title: Предупреждение
    color: red
  note:
    title: Информация
    color: purple

mermaid:
  version: "10.9.0"